### ISSUE TITLE
First phase storm timer bugs

### ISSUE THREAD

**Issue by AitorSimona** [CheckTheDog/Fantasy-Brawl#12]
Bug Type:
Description:

(Desribe the bug here)

Fatal ()
Unintended action (X)
Aesthetic ()

Priority:

ASAP ()
High ()
Medium (X)
Low ()

Frequency:

Everytime (X)
Regular ()
Low ()

Reproduction:
While the storm is MOVING, press ESC and start a new game, the storm should come close faster

Expected behavior:
Shouldn't happen :).

Actual behavior:
Comes in sooner.

Game version:

0.5.2

Additional context:

(Screenshots, others here)

Suggested Assignees:

Didac

**Comment by DidacRomero** [comment]
Fixed the bug, QA can check and close the issue. Some values had to be restarted and where not restarted.

**Comment by DidacRomero** [comment]
The Issue will now be closed
