### ISSUE TITLE
Gamepad new connection after game start makes P1 control everything

### ISSUE THREAD

**Issue by DidacRomero** [CheckTheDog/Fantasy-Brawl#9]
Bug Type:
Description:
If there's a gamepad connected to the PC, the game is running and we connect another gamepad, the entity that should be controlled by the new gamepad, is controlled by the previously connected gamepad.

Example: Player 1 (P1) is playing with his/her gamepad connected. P2 connects the gamepad, the entity of P2 is controlled by P1.

Fatal (x)
Unintended action ()
Aesthetic ()

Priority:

ASAP ()
High (x)
Medium ()
Low ()

Frequency:

Everytime (x)
Regular ()
Low ()

Reproduction:

1- Connect 1 gamepad and start the game
2- While playing, connect another gamepad to play as player 2

The bug has now been triggered
3- Try to move with  the new player, only the previous player controlls the new one.
Expected behavior:

Player 2 can play with the new gamepad connected.

Actual behavior:

Player 1 also controls Player 2

Game version:

``v0.1``

Additional context:

Suggested Assignees:

@DidacRomero 
@AitorSimona

**Comment by DidacRomero** [comment]
It seems the error might be just if you plug Sony Controller devices, which already gave problems with the haptic features. I've tried in debug, release, and release in the game and i don't have any problems with the 2 Xbox controllers.

**Comment by Xulu-u** [comment]
Game is meant to be played with Xbox controllers, ps4 controllers support not relevant atm
